---
extends: default

rules:
  line-length:
    max: 120
    level: warning

  comments:
    min-spaces-from-content: 1
  # ansible-lintとの互換性のため追加
  comments-indentation: false
  
  braces:
    max-spaces-inside: 1
    
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
