name: ROS2 Build and Test

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - 'ansible/**'
      - 'docker/**'
      - 'scripts/**'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - 'ansible/**'
      - 'docker/**'
      - 'scripts/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: 
      image: ros:${{ matrix.ros_distro }}-ros-base
      options: --platform linux/amd64
    env:
      DEBIAN_FRONTEND: noninteractive
      SHELL: /bin/bash
    strategy:
      matrix:
        ros_distro: [humble, jazzy]
      fail-fast: false
    
    steps:
    - name: Suppress git warnings
      run: |
        git config --global --add safe.directory '*'
        
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install build dependencies
      run: |
        apt-get update && apt-get install -y \
          python3-colcon-common-extensions \
          python3-pip \
          python3-vcstool \
          ccache \
          git \
          wget \
          && rm -rf /var/lib/apt/lists/*

    - name: Configure git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git config --global init.defaultBranch main
        git config --global --add safe.directory $(pwd)

    - name: Setup workspace and dependencies
      run: |
        # Create workspace structure
        mkdir -p src
        
        # Copy ROS2 package directories to workspace
        for pkg in ddt_motor_control ddt_motor_control_cpp esc_motor_control esc_motor_control_python joy_controller servo_control_ros2; do
          if [ -d "$pkg" ]; then
            echo "Copying package: $pkg"
            cp -r "$pkg" src/
          fi
        done
        
        # Copy launcher package if it exists
        if [ -d "launcher" ]; then
          echo "Copying launcher package"
          cp -r "launcher" src/
        fi
        
        # Import additional repositories if dependency.repos exists
        if [ -f dependency.repos ]; then
          echo "Importing dependencies from dependency.repos"
          # Configure git to use HTTPS instead of SSH for GitHub
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          vcs import src < dependency.repos
        fi
        
        # List discovered packages
        echo "Discovered packages:"
        find src -name package.xml -exec dirname {} \;

    - name: Generate rosdep keys
      run: |
        # Initialize rosdep if not already done
        rosdep init || echo "rosdep already initialized"
        rosdep update
        
        # Generate package list and rosdep keys
        if [ -d "src" ] && [ "$(find src -name package.xml | wc -l)" -gt 0 ]; then
          colcon list -p --base-paths src > packages.txt
          rosdep keys --from-paths $(cat packages.txt) --rosdistro ${{ matrix.ros_distro }} > rosdep_keys.txt || echo "No rosdep keys found"
        else
          echo "No packages found in src directory"
          touch rosdep_keys.txt
        fi

    - name: Cache rosdep
      id: cache-rosdep
      uses: actions/cache@v4
      with:
        path: |
          /var/lib/apt/lists
          /root/.ros/rosdep
        key: rosdep-${{ matrix.ros_distro }}-${{ runner.os }}-${{ hashFiles('rosdep_keys.txt') }}
        restore-keys: |
          rosdep-${{ matrix.ros_distro }}-${{ runner.os }}-

    - name: Install package dependencies
      run: |
        if [[ "${{ steps.cache-rosdep.outputs.cache-hit }}" == "true" ]]; then
          echo "Rosdep cache hit. Skipping rosdep install."
        else
          echo "Rosdep cache miss. Running rosdep install."
          apt-get -yqq update
          # Check if we have any packages to install dependencies for
          if [ -d "src" ] && [ "$(find src -name package.xml | wc -l)" -gt 0 ]; then
            rosdep install -yqq --from-paths src --ignore-src --rosdistro ${{ matrix.ros_distro }} || echo "Some rosdep dependencies could not be installed"
          else
            echo "No packages found for dependency installation"
          fi
        fi

    - name: Install Python dependencies
      run: |
        # Install python3-serial package for ROS 2 dependencies
        apt-get update && apt-get install -y python3-serial && rm -rf /var/lib/apt/lists/*

    - name: Setup colcon mixin
      run: |
        colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml || true
        colcon mixin update default || true

    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          build
          install
        key: build-${{ matrix.ros_distro }}-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', '**/package.xml') }}
        restore-keys: |
          build-${{ matrix.ros_distro }}-${{ runner.os }}-

    - name: Build ROS2 packages
      shell: bash
      run: |
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        
        # Check if we have packages to build
        if [ ! -d "src" ] || [ "$(find src -name package.xml | wc -l)" -eq 0 ]; then
          echo "No ROS2 packages found to build"
          exit 1
        fi
        
        # Use optimized parallel workers for GitHub Actions
        PARALLEL_WORKERS=$(nproc)
        echo "Using $PARALLEL_WORKERS parallel workers for build"
        
        # List packages to be built
        echo "Packages to be built:"
        colcon list --base-paths src
        
        # Build with optimizations
        colcon build \
          --event-handlers console_cohesion+ \
          --parallel-workers $PARALLEL_WORKERS \
          --cmake-args -DCMAKE_BUILD_TYPE=Release \
          --symlink-install

    - name: Run tests
      shell: bash
      run: |
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        
        # Check if install directory exists
        if [ ! -d "install" ]; then
          echo "No install directory found, skipping tests"
          exit 0
        fi
        
        source install/setup.bash
        
        # Check if there are any test targets
        if colcon list | grep -q .; then
          echo "Running tests for packages:"
          colcon list
          colcon test \
            --event-handlers console_cohesion+ \
            --parallel-workers $(nproc) \
            --return-code-on-test-failure
        else
          echo "No packages found for testing"
        fi

    - name: Show test results
      if: always()
      shell: bash
      run: |
        if [ -d "install" ]; then
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          source install/setup.bash
          colcon test-result --verbose || echo "No test results found"
        else
          echo "No install directory found, no test results to show"
        fi

  static-analysis:
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.ros_distro }}-ros-base
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        ros_distro: [humble, jazzy]
    steps:
    - name: Suppress git warnings
      run: git config --global --add safe.directory '*'
        
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install linting tools
      run: |
        apt-get update && apt-get install -y python3-pip python3-flake8 && rm -rf /var/lib/apt/lists/*
        pip3 install --break-system-packages pep257 || apt-get update && apt-get install -y python3-pep257 && rm -rf /var/lib/apt/lists/*

    - name: Run flake8 (Python style check)
      run: |
        # Find Python files and run flake8
        python_files=$(find . -name "*.py" -not -path "./__pycache__/*" -not -path "./build/*" -not -path "./install/*" -not -path "./log/*" -not -path "./.git/*")
        if [ -n "$python_files" ]; then
          echo "Running flake8 on Python files:"
          echo "$python_files"
          echo "$python_files" | xargs flake8 --max-line-length=100 --ignore=E501,W503
        else
          echo "No Python files found for style checking"
        fi

    - name: Run pep257 (Python docstring check)
      run: |
        # Find Python files and run pep257
        python_files=$(find . -name "*.py" -not -path "./__pycache__/*" -not -path "./build/*" -not -path "./install/*" -not -path "./log/*" -not -path "./.git/*")
        if [ -n "$python_files" ]; then
          echo "Running pep257 on Python files:"
          echo "$python_files"
          echo "$python_files" | xargs pep257 --ignore=D100,D101,D102,D103,D104,D105,D107,D203,D213 || echo "pep257 completed with warnings"
        else
          echo "No Python files found for docstring checking"
        fi

  format-check:
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.ros_distro }}-ros-base
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        ros_distro: [humble, jazzy]
    if: github.event_name == 'pull_request'
    steps:
    - name: Suppress git warnings
      run: git config --global --add safe.directory '*'
        
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install ament_clang_format
      run: |
        apt-get update && apt-get install -y \
          python3-pip \
          ros-dev-tools \
          && rm -rf /var/lib/apt/lists/*
        pip3 install --break-system-packages ament_clang_format || \
        apt-get update && apt-get install -y ros-${{ matrix.ros_distro }}-ament-clang-format && rm -rf /var/lib/apt/lists/*

    - name: Check C++ formatting
      run: |
        # Find C++ files and check formatting
        cpp_files=$(find . -name "*.cpp" -o -name "*.hpp" -o -name "*.h" -o -name "*.cc" | grep -v build | grep -v install | grep -v log)
        if [ -n "$cpp_files" ]; then
          echo "Checking C++ formatting for files:"
          echo "$cpp_files"
          if which ament_clang_format > /dev/null 2>&1; then
            echo "$cpp_files" | xargs ament_clang_format --config .clang-format --reformat-code=false
          elif which clang-format > /dev/null 2>&1; then
            echo "Using clang-format as fallback"
            echo "$cpp_files" | xargs clang-format --dry-run --Werror
          else
            echo "No C++ formatter available, skipping format check"
          fi
        else
          echo "No C++ files found for formatting check"
        fi

  build-summary:
    needs: [build-and-test, static-analysis, format-check]
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    env:
      DEBIAN_FRONTEND: noninteractive
    if: always()
    steps:
    - name: Build Summary
      run: |
        echo "## Build Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ needs.build-and-test.result }}" == "success" ]; then
          echo "✅ **Build and Test**: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Build and Test**: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.static-analysis.result }}" == "success" ]; then
          echo "✅ **Static Analysis**: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Static Analysis**: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.format-check.result }}" == "success" ] || [ "${{ needs.format-check.result }}" == "skipped" ]; then
          echo "✅ **Format Check**: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Format Check**: Failed" >> $GITHUB_STEP_SUMMARY
        fi
